name: Python FAIR Data Pipeline
on: [push]
jobs:
  test:
    name: Test ${{ matrix.os }} (Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python: ["3.8","3.9"]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install Required
        run: brew install memcached
        if: matrix.os == 'macos-latest'
      - name: Install and Run Model
        run: |
          pip install fair-cli
          fair registry install
          pip install data-pipeline-api
          pip install .
          fair init --ci --local
          fair registry start
          fair pull --local simpleModel/ext/SEIRSconfig.yaml
          fair run --local simpleModel/ext/SEIRSconfig.yaml
